public enum EventIds
{
    StartGamePressed,
    NoContinue,
    NextLevel,
    GoToHighScore,
    BackToMenu,
    GameOver,
    Victory,
    RestartPressed,
    EnemyDestroyed,
    EnemySpawned,
    AllEnemiesSpawned,
    PlayerSpawned,
    PlayerDestroyed,
    RestartLevelComplete,
    SpawnPowerUp,
    ScoreUpdated,
    CanShoot
}
